<a href="https://colab.research.google.com/github/Principiante-en-Programacion-G8-ONE/Challenge-Amigo-secreto/blob/master/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [193]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [ ]:
ingreso_tienda = tienda['Precio'].sum()
ingreso_tienda_2 = tienda2['Precio'].sum()
ingreso_tienda_3 = tienda3['Precio'].sum()
ingreso_tienda_4 = tienda4['Precio'].sum()
ingreso_tienda, ingreso_tienda_2, ingreso_tienda_3, ingreso_tienda_4

(np.float64(1150880400.0),
 np.float64(1116343500.0),
 np.float64(1098019600.0),
 np.float64(1038375700.0))

# 2. Ventas por categoría

In [ ]:
total_por_categoria = tienda.groupby('Categoría del Producto')['Precio'].sum()
total_por_categoria_2 = tienda2.groupby('Categoría del Producto')['Precio'].sum()
total_por_categoria_3 = tienda3.groupby('Categoría del Producto')['Precio'].sum()
total_por_categoria_4 = tienda4.groupby('Categoría del Producto')['Precio'].sum()

In [ ]:
total_por_categoria

Categoría del Producto
Artículos para el hogar     12698400.0
Deportes y diversión        39290000.0
Electrodomésticos          363685200.0
Electrónicos               429493500.0
Instrumentos musicales      91299000.0
Juguetes                    17995700.0
Libros                       8784900.0
Muebles                    187633700.0
Name: Precio, dtype: float64

In [ ]:
total_por_categoria_2

Categoría del Producto
Artículos para el hogar     14746900.0
Deportes y diversión        34744500.0
Electrodomésticos          348567800.0
Electrónicos               410831100.0
Instrumentos musicales     104990300.0
Juguetes                    15945400.0
Libros                      10091200.0
Muebles                    176426300.0
Name: Precio, dtype: float64

In [ ]:
total_por_categoria_3

Categoría del Producto
Artículos para el hogar     15060000.0
Deportes y diversión        35593100.0
Electrodomésticos          329237900.0
Electrónicos               410775800.0
Instrumentos musicales      77380900.0
Juguetes                    19401100.0
Libros                       9498700.0
Muebles                    201072100.0
Name: Precio, dtype: float64

In [ ]:
total_por_categoria_4

Categoría del Producto
Artículos para el hogar     15074500.0
Deportes y diversión        33350100.0
Electrodomésticos          283260200.0
Electrónicos               409476100.0
Instrumentos musicales      75102400.0
Juguetes                    20262200.0
Libros                       9321300.0
Muebles                    192528900.0
Name: Precio, dtype: float64

# 3. Calificación promedio de la tienda

In [213]:
calificacion_promedio = {
    'Tienda 1': tienda['Calificación'].mean(),
    'Tienda 2': tienda2['Calificación'].mean(),
    'Tienda 3': tienda3['Calificación'].mean(),
    'Tienda 4': tienda4['Calificación'].mean()
}
tb_calificacion_promedio = pd.DataFrame.from_dict(calificacion_promedio, orient='index', columns=['Calificación promedio'])
tb_calificacion_promedio

          Calificación promedio
Tienda 1               3.976685
Tienda 2               4.037304
Tienda 3               4.048326
Tienda 4               3.995759

# 4. Productos más y menos vendidos

In [ ]:
ventas_productos = tienda['Producto'].value_counts()
ventas_productos_2 = tienda2['Producto'].value_counts()
ventas_productos_3 = tienda3['Producto'].value_counts()
ventas_productos_4 = tienda4['Producto'].value_counts()

In [ ]:
cantidad_maxima = ventas_productos.max()
cantidad_minima = ventas_productos.min()
venta_mayor = ventas_productos[ventas_productos == cantidad_maxima].index.tolist()
venta_menor = ventas_productos[ventas_productos == cantidad_minima].index.tolist()
print(f'Tienda 1 \nProductos mas vendidos: \n {venta_mayor} \nProductos menos vendidos \n {venta_menor}')

Tienda 1
Productos mas vendidos:
 ['Microondas', 'TV LED UHD 4K', 'Armario']
Productos menos vendidos
 ['Auriculares con micrófono', 'Celular ABXY']

In [ ]:
cantidad_maxima_2 = ventas_productos_2.max()
cantidad_minima_2 = ventas_productos_2.min()
venta_mayor_2 = ventas_productos_2[ventas_productos_2 == cantidad_maxima_2].index.tolist()
venta_menor_2 = ventas_productos_2[ventas_productos_2 == cantidad_minima_2].index.tolist()
print(f'Tienda 2 \nProductos mas vendidos: \n {venta_mayor_2} \nProductos menos vendidos \n {venta_menor_2}')

Tienda 2
Productos mas vendidos:
 ['Iniciando en programación']
Productos menos vendidos
 ['Juego de mesa']

In [ ]:
cantidad_maxima_3 = ventas_productos_3.max()
cantidad_minima_3 = ventas_productos_3.min()
venta_mayor_3 = ventas_productos_3[ventas_productos_3 == cantidad_maxima_3].index.tolist()
venta_menor_3 = ventas_productos_3[ventas_productos_3 == cantidad_minima_3].index.tolist()
print(f'Tienda 3 \nProductos mas vendidos: \n {venta_mayor_3} \nProductos menos vendidos \n {venta_menor_3}')

Tienda 3
Productos mas vendidos:
 ['Kit de bancas']
Productos menos vendidos
 ['Bloques de construcción']

In [ ]:
cantidad_maxima_4 = ventas_productos_4.max()
cantidad_minima_4 = ventas_productos_4.min()
venta_mayor_4 = ventas_productos_4[ventas_productos_4 == cantidad_maxima_4].index.tolist()
venta_menor_4 = ventas_productos_4[ventas_productos_4 == cantidad_minima_4].index.tolist()
print(f'Tienda 4 \nProductos mas vendidos: \n {venta_mayor_4} \nProductos menos vendidos \n {venta_menor_4}')

Tienda 4
Productos mas vendidos:
 ['Cama box']
Productos menos vendidos
 ['Guitarra eléctrica']

# 5. Envío promedio por tienda

In [194]:
tienda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [212]:
costo_envio_promedio = {
    'Tienda 1': tienda['Costo de envío'].mean(),
    'Tienda 2': tienda2['Costo de envío'].mean(),
    'Tienda 3': tienda3['Costo de envío'].mean(),
    'Tienda 4': tienda4['Costo de envío'].mean()
}

tb_costo_envio_promedio = pd.DataFrame.from_dict(costo_envio_promedio, orient='index', columns=['Costo de envío promedio'])
tb_costo_envio_promedio

          Costo de envío promedio
Tienda 1             26018.609580
Tienda 2             25216.235693
Tienda 3             24805.680373
Tienda 4             23459.457167